# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Zip Release
          # You may pin to the exact commit or the version.
          # uses: TheDoctor0/zip-release@a1afcab9c664c9976ac398fa831eac67bed1eb0e
        uses: TheDoctor0/zip-release@0.4.1
        with:
          # Filename for archive
          filename: balanced_alliances.zip
          # Base path for archive files
          path: .
          # Working directory before zipping
          directory: common
          # List of excluded files / directories
          exclusions: '*.git'
          # Tool to use for archiving
          type: zip
      - uses: actions/checkout@v2

      - run: mkdir -p path/to/artifact

      - run: echo hello > world.txt
      - name: Upload Zip
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: world.txt
